Close button accessibility
mercadolibre/MLDynamicModal pull request #8
Opened 2020-05-27 14:49 UTC by iaguero

Se agrega función setCloseBtnAccessibility para hacer accesible el botón cerrar haciendo configurable la etiqueta de accesibilidad.

Se modifica: 
* MLDynamicModal/Classes/MLDynamicModalViewController.h
* MLDynamicModal/Classes/MLDynamicModalViewController.m

Se agregan test:
* Example/Tests/Tests.m

2020-05-27 15:03 UTC, nicolasfrugoni requested changes

2020-05-27 15:03 UTC, nicolasfrugoni commented on MLDynamicModal/Classes/MLDynamicModalViewController.m
> +@property (nullable,strong,nonatomic) UIBarButtonItem *closeBtn;
hagamos que sea una variable privada del metodo, mira el comment de abajo

2020-05-27 15:03 UTC, nicolasfrugoni commented on MLDynamicModal/Classes/MLDynamicModalViewController.m
> +@property (nonatomic) BOOL shouldMakeCloseBtnAccessible;
Creo que sacaria esta variable, que se decida si ponerle accesibility o no segun haya o no accesibility label

2020-05-27 15:03 UTC, nicolasfrugoni commented on MLDynamicModal/Classes/MLDynamicModalViewController.m
> +- (void)setCloseBtnAccessibility:(NSString *_Nonnull)accessibilityLabel
hagamos que este metodo reciba un UIView ademas del String, para que no haga falta que el boton sea una variable de clase (ademas quedaria reutilizable)

```
-(void)setAccessibilityLabel:(NSString *)accesibilityLabel onView:(UIView *)aView {
    aView.isAccessibilityElement = YES;
    aView.accessibilityLabel = accessibilityLabel
}
```

2020-05-27 15:03 UTC, nicolasfrugoni commented on MLDynamicModal/Classes/MLDynamicModalViewController.m
> +        }
Esto se puede hacer abajo en el metodo `configureCloseButtonWithColor`

2020-05-27 15:03 UTC, nicolasfrugoni commented on MLDynamicModal/Classes/MLDynamicModalViewController.m
>                                                                  action:@selector(closeButtonPressed)];
aca despues de instanciarlo, podes llamar al metodo

```
[self setAccessibilityLabel:self.closeBtnAccessibilityLabel onView:closeButton];
```

2020-05-27 17:04 UTC, nicolasfrugoni approved these changes

2020-05-27 20:14 UTC, nicolasfrugoni approved these changes

2020-05-28 14:57 UTC, jonurq approved these changes

2020-05-28 14:58 UTC, merged